version: 2
updates:
- package-ecosystem: terraform
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
    timezone: Australia/Sydney
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 5
  labels:
    - "dependencies"
